create extension if not exists "pgcrypto";

create type public.app_role as enum ('customer', 'admin');
create type public.product_status as enum ('draft', 'active', 'archived');
create type public.order_status as enum ('draft', 'pending_payment', 'paid', 'fulfilled', 'cancelled', 'refunded');

create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  full_name text,
  avatar_url text,
  role public.app_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid references public.categories (id) on delete set null,
  slug text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references public.categories (id) on delete set null,
  slug text not null unique,
  sku text unique,
  name text not null,
  short_description text,
  description text,
  status public.product_status not null default 'draft',
  currency text not null default 'HUF',
  base_price numeric(12, 2) not null default 0,
  compare_at_price numeric(12, 2),
  seo_title text,
  seo_description text,
  featured_image_url text,
  track_inventory boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  url text not null,
  alt_text text,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_options (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  name text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (product_id, name)
);

create table if not exists public.product_option_values (
  id uuid primary key default gen_random_uuid(),
  option_id uuid not null references public.product_options (id) on delete cascade,
  value text not null,
  label text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (option_id, value)
);

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  sku text not null unique,
  name text not null,
  price numeric(12, 2) not null,
  compare_at_price numeric(12, 2),
  stock_quantity integer not null default 0,
  is_default boolean not null default false,
  is_active boolean not null default true,
  stripe_price_id text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variant_option_values (
  variant_id uuid not null references public.product_variants (id) on delete cascade,
  option_value_id uuid not null references public.product_option_values (id) on delete cascade,
  primary key (variant_id, option_value_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  user_id uuid references public.users (id) on delete set null,
  email text not null,
  status public.order_status not null default 'draft',
  currency text not null default 'HUF',
  subtotal numeric(12, 2) not null default 0,
  tax_total numeric(12, 2) not null default 0,
  shipping_total numeric(12, 2) not null default 0,
  grand_total numeric(12, 2) not null default 0,
  shipping_address jsonb,
  billing_address jsonb,
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,
  variant_id uuid references public.product_variants (id) on delete set null,
  product_name text not null,
  variant_name text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null,
  line_total numeric(12, 2) not null,
  snapshot jsonb not null default '{}'::jsonb
);

create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  store_name text not null,
  currency text not null default 'HUF',
  tax_rate numeric(5, 2) not null default 27,
  support_email text not null,
  locale text not null default 'hu-HU',
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_auth_user();

drop trigger if exists touch_users_updated_at on public.users;
create trigger touch_users_updated_at before update on public.users
for each row execute procedure public.touch_updated_at();

drop trigger if exists touch_categories_updated_at on public.categories;
create trigger touch_categories_updated_at before update on public.categories
for each row execute procedure public.touch_updated_at();

drop trigger if exists touch_products_updated_at on public.products;
create trigger touch_products_updated_at before update on public.products
for each row execute procedure public.touch_updated_at();

drop trigger if exists touch_variants_updated_at on public.product_variants;
create trigger touch_variants_updated_at before update on public.product_variants
for each row execute procedure public.touch_updated_at();

drop trigger if exists touch_orders_updated_at on public.orders;
create trigger touch_orders_updated_at before update on public.orders
for each row execute procedure public.touch_updated_at();

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1
    from public.users
    where id = uid and role = 'admin'
  );
$$;

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_options enable row level security;
alter table public.product_option_values enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_variant_option_values enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.store_settings enable row level security;

create policy "Public can read active categories"
on public.categories
for select
using (true);

create policy "Public can read active products"
on public.products
for select
using (status = 'active');

create policy "Public can read product images"
on public.product_images
for select
using (true);

create policy "Public can read product options"
on public.product_options
for select
using (true);

create policy "Public can read product option values"
on public.product_option_values
for select
using (true);

create policy "Public can read active variants"
on public.product_variants
for select
using (is_active = true);

create policy "Public can read variant option mapping"
on public.product_variant_option_values
for select
using (true);

create policy "Users can read their profile"
on public.users
for select
using (auth.uid() = id or public.is_admin(auth.uid()));

create policy "Users can update their profile"
on public.users
for update
using (auth.uid() = id);

create policy "Admins manage catalog"
on public.products
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins manage categories"
on public.categories
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins manage catalog images"
on public.product_images
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins manage product options"
on public.product_options
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins manage option values"
on public.product_option_values
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins manage variants"
on public.product_variants
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins manage variant mapping"
on public.product_variant_option_values
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Customers read own orders"
on public.orders
for select
using (auth.uid() = user_id or public.is_admin(auth.uid()));

create policy "Admins manage orders"
on public.orders
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Customers read own order items"
on public.order_items
for select
using (
  exists (
    select 1
    from public.orders
    where public.orders.id = order_items.order_id
      and (public.orders.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

create policy "Admins manage order items"
on public.order_items
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Public can read store settings"
on public.store_settings
for select
using (true);

create policy "Admins manage store settings"
on public.store_settings
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

insert into public.store_settings (id, store_name, currency, tax_rate, support_email, locale)
values (1, 'Northstar Commerce', 'HUF', 27, 'support@northstar-commerce.test', 'hu-HU')
on conflict (id) do nothing;
